---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: vault-linkerd-issuer
  namespace: cert-manager
spec:
  vault:
    server: http://vault.vault:8200
    path: pki_int/root/sign-intermediate
    auth:
      kubernetes:
        mountPath: /v1/auth/kubernetes
        role: vault-issuer
        secretRef:
          name: vault-issuer-token
          key: token
