apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: hashicup
  namespace: apps
spec:
  interval: 1m
  url: https://github.com/channyein87/gitops-hashicups
  ref:
    branch: main
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: hashicup
  namespace: apps
spec:
  serviceAccountName: hashicup
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: hashicup
  prune: true
