spec:
  destination:
    server: https://kubernetes.default.svc
  source:
    repoURL: ${GITOPS_REPO_URL_ARGOCD}
    targetRevision: main

applications:
  - name: assets
  - name: carts
  - name: catalog
  - name: checkout
  - name: orders
  - name: other
  - name: rabbitmq
  - name: ui
