apiVersion: v2
appVersion: 25.9.1
name: linkerd
version: 1.0.5
description: Umbrella chart to deploy the linkerd and supporting objects

dependencies:
  - name: linkerd-crds
    version: 2025.9.1
    repository: https://helm.linkerd.io/edge
  - name: linkerd-control-plane
    version: 2025.9.1
    repository: https://helm.linkerd.io/edge
