apiVersion: platform.confluent.io/v1beta1
kind: Kafka
metadata:
  name: kafka
  namespace: confluent
spec:
  replicas: 3
  image:
    application: confluentinc/cp-server:7.5.0
    init: confluentinc/confluent-init-container:2.7.0
  dataVolumeCapacity: 100Gi
  configOverrides:
    server:
      - confluent.cluster.link.enable=true
  listeners:
    external:
      externalAccess:
        type: loadBalancer
        loadBalancer:
          domain: lab.awscontoso.com
          annotations:
            service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
            service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
          labels:
            ingress: externaldns
  metricReporter:
    enabled: true
    bootstrapEndpoint: kafka:9071
  dependencies:
    zookeeper:
      endpoint: zookeeper.confluent.svc.cluster.local:2181