name: Deploy

on:
  workflow_dispatch:
    inputs:
      stack:
        description: 'Stack name'
        required: true
        default: 'linkerd'
        type: choice
        options:
        - linkerd
        - atlantis
        - fluxcd
      apply:
        description: 'Apply'
        required: false
        default: true
        type: boolean

jobs:
  terraform-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        working-directory: ${{ inputs.stack }}
        run: terraform init

      - name: Terraform Plan
        working-directory: ${{ inputs.stack }}
        run: |
          echo "${{ secrets.TF_VARS }}" > terraform.tfvars
          terraform plan -input=false -out=tfplan

      - name: Terraform Apply
        working-directory: ${{ inputs.stack }}
        if: github.ref_name == 'main' && inputs.apply == true
        run: terraform apply -auto-approve -input=false tfplan
