name: Destroy

on:
  workflow_dispatch:
    inputs:
      stack:
        description: 'Stack name'
        required: true
        default: 'linkerd'
        type: choice
        options:
        - linkerd
        - atlantis
        - fluxcd
        - confluent
      destroy:
        description: 'Destroy'
        required: false
        default: true
        type: boolean

jobs:
  terraform-destroy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        working-directory: ${{ inputs.stack }}
        run: |
          cat <<EOF >>backend.tf
          terraform {
            backend "s3" {}
          }
          EOF
          terraform init \
            -backend-config="bucket=terragrunt-terraform" \
            -backend-config="key=lab/${{ inputs.stack }}/terraform.tfstate" \
            -backend-config="region=ap-southeast-2"

      - name: Terraform Plan
        working-directory: ${{ inputs.stack }}
        run: |
          cat <<EOF >>terraform.tfvars
          ${{ secrets.TF_VARS }}
          EOF
          terraform plan -destroy

      - name: Terraform Destroy
        working-directory: ${{ inputs.stack }}
        if: inputs.destroy == true
        run: terraform destroy -auto-approve -input=false
