name: Destroy

on:
  workflow_dispatch:
    inputs:
      stack:
        description: 'Stack name'
        required: true
        default: 'linkerd'
        type: choice
        options:
        - linkerd
        - atlantis
        - fluxcd

jobs:
  terraform-destroy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        working-directory: ${{ inputs.stack }}
        run: terraform init

      - name: Terraform Destroy
        working-directory: ${{ inputs.stack }}
        if: github.ref_name == 'main'
        run: |
          echo "${{ secrets.TF_VARS }}" > terraform.tfvars
          terraform destroy -auto-approve -input=false
